### ISSUE TITLE
Twitter Tool

### ISSUE THREAD

**Issue by ThomasThelen** [balliam/python-examples#2]
Create a python application that accepts a user entering a twitter hashtag (wihout the #). Use [tweepy](https://github.com/tweepy/tweepy) to output the number of tweets with that hashtag from the last 24 hours and write the tweets to a text file. You could imagine a researcher using the text file to feed data to a model. Tweepy has a nice community and discord server for questions, but feel free to ask them here too.

**Comment by balliam** [comment]
Not to familiar with twitter. Is the '#' just a search keyword? im looking through the tweepy API doc and not seeing much about that. only really seeing search tweets

**Comment by ThomasThelen** [comment]
Right- hash fragments in Twitter are kind of like a way to add keywords to a tweet-so essentially just a search. You should find some good information [here](shorturl.at/cvRTX). If it's a bit too confusing feel free to move onto the next issue

**Comment by balliam** [comment]
I uploaded what ive got done. still need to mess around with creating files and saving output to them. i can come back to it later on down the road
