### ISSUE TITLE
Sorting a list

### ISSUE THREAD

**Issue by ThomasThelen** [balliam/python-examples#3]
Create a python program that....

1. Takes 10 numbers from the user input and inserts them in a list
1. Has a function named `sort` that takes a list of numbers and a flag for sorting low to high (1,2,3,4...)
2. Sort the user input and display it on the screen

When the sorting flag is false, sort the numbers high to low (10, 9, 8, 7, ...)

**Comment by balliam** [comment]
I believe i got the input and adding it to a list but seeming to have a issue with using the sort() on the list. ex: list1.sort()

**Comment by ThomasThelen** [comment]
Sweet! Upload the code and I'll take a peek

**Comment by balliam** [comment]
Uploaded. When i press q and enter that the result is "None"

**Comment by ThomasThelen** [comment]
Ah this is a fun one. Some data structures (str, list, int, dict, etc) are _mutable_, while others aren't. For example, 

```
my_str: str = "Hello"
my_str + "World"
print(my_str)
```
will print "Hello", because strings aren't mutable. Lists are, so when you call my_list.sort()-it's actually mutating the list.

More info... https://www.geeksforgeeks.org/mutable-vs-immutable-objects-in-python/

Instead of `print(list1.sort())`, you'd want

```
list1.sort()
print(list1)
```

**Comment by balliam** [comment]
Actually uploaded a fix. seems to be all working now
