### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by ThomasThelen** [balliam/python-examples#4]
Python has the built in `sort` method. Instead of using this method, write a function that takes a list and does a bubble sort to manually sort the list.

**Comment by balliam** [comment]
Uploaded a temp file for this.

**Comment by balliam** [comment]
Also i think i might try messing around with front end stuff too. i wanna try and switch jobs some what soon and i've heard that it's easier to get into like html/js jobs. What do you think

**Comment by ThomasThelen** [comment]
It depends where your skills are-if you're better at backend, it would be harder to get a job a a frontend dev. I'd say go for learning a framework like React and making an API with Python (FastAPI/Django)

**Comment by balliam** [comment]
Well i'm not to sure at all lol. Which do you think is the fast path to get a job in this role? i'm looking to get out of my crappy current job asap 😣

**Comment by ThomasThelen** [comment]
I would say around 6 months of active, persistent studying of CS fundamentals like data structures and algorithms along with practical project experience would give you a starting chance. Most coding interviews will be on data structure type problems and people generally won't believe you can program unless you have work to show for it. Bonus points if you already have a degree in STEM

**Comment by balliam** [comment]
I'm def really enjoying learning all of this. It has really caught my attention

**Comment by balliam** [comment]
finally added a descending sort function
